apiVersion: v1
kind: Secret
metadata:
  name: vcluster-secret
  namespace: {{ .Values.argocdNamespace }}
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: my-vcluster
  server: "https://{{ .Release.Name }}.{{ .Release.Namespace }}"
  config: |
    {
      "execProviderConfig": {
        "command": "sh",
        "args": [
          "-c",
          "kubectl get secret vc-{{ .Release.Name }} -n {{ .Release.Namespace }} --template={{.data.config}} | base64 -D"
        ]
      }
    }
